version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=admin
    volumes:
      - "db-data:/var/lib/postgresql/data"
  app:
    image: r1mok/shbrproject
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mydb
    depends_on:
      - postgres
    ports:
      - "80:8080"
volumes:
  db-data: