spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/}
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
server:
  port: ${PORT:80}